### ISSUE TITLE
masterSwitch can be left on if nightlight is not on

### ISSUE THREAD

**Issue by philipfong** [corphish/NightLight#14]
Steps to repro:
1. Go into app and ensure the switch is off.
2. Toggle night light on from the quick tray
3. Toggle night light off from the quick tray
4. Open the app and the masterSwitch is still on

Possibly related to somewhere around `StartActivity.java` line 83

**Comment by corphish** [comment]
Quick tray toggle doesn't sync with master switch, although when user turns it on using the toggle, it does turn on master switch because, had it not turned on the master switch (if it was off), night light wont be turned on, which would lead to a bad UX actually, as the user would then have to go to the app, turn on master switch, and then the toggle would function as expected. So yeah, _toggle when turned on, turns on the master switch just in case, as the user would expect the night light to be enabled when he/she toggles it on._
When it is toggled off from the quick tray, it doesn't turn off master switch, because if the situation be like the user is using automatic schedule for night light, but decides to turn it on outside the schedule (from toggle) and then turn it off (using the toggle), (and toggling off actually turns off the master switch), then automated schedule won't work, as master switch is needed to be on for automatic schedule to work.
If automatic schedule did not depend on master switch, it would enable night light even if user had opted out of it.

I might consider syncing the toggle with the force switch, I think that would make more sense. If you have a better idea, feel free to mention :).

**Comment by philipfong** [comment]
That makes sense.  The master switch toggle has much broader functionality than the quick tray toggle.  Closing this one then.
