### ISSUE TITLE
Setting custom KCAL values?

### ISSUE THREAD

**Issue by ghost** [corphish/NightLight#26]
There's a feature in CF.Lumen where you can set up the app to use custom KCAL values instead of using colour temperature.

This would be very helpful for me in this app as the device I use (the Moto G4) has an issue with screen retention which is prevented by setting all the KCAL values to below ~215, and also the lowest the colour temperature can be set in this app is 4500k (when I would like it at 1500k at night 😄).

**Comment by corphish** [comment]
You can set the app to use custom KCAL values, instead of using color temperature.
* Enable master switch (if not already) to see the settings.
* Tap `Color Controls`.
* Enable `Manual Mode` switch, which then enables you to set your own KCAL RGB values.

Also, an update was released yesterday which increases the color temperature range from 3000K - 4500K to 2500K - 5000K. Although its not as low as you mentioned, it might still be useful if you choose to use temperature setting.
