### ISSUE TITLE
Warning about overalapping time routine

### ISSUE THREAD

**Issue by march5350** [corphish/NightLight#32]
When I create a first routine I can set every time I want. But with the creation of a second routine I always get notified that the time is overlapping with an other routine. Even if this is not the case. 

I use version 3.0.0-pre-beta-06 (59)

**Comment by corphish** [comment]
Hi! Could you tell the times that you were setting for the first and the second routine?

**Comment by march5350** [comment]
Sure. I have one routine going from sunset to 23:59. The second routine I would like to add runs from 00:00 to sunrise. I can add the starting time, but when I enter the end time it states that the times are overlapping.

**Comment by corphish** [comment]
Very nice and important catch, even I was able to reproduce the same. This has been fixed in https://github.com/corphish/NightLight/commit/970580e457c1de4114679069e7532fbf4b6d7f01 ... https://github.com/corphish/NightLight/commit/4e1e8976c96138fbaa0ffdb2517136c6cb647470, and should now work as expected. The fixes will be available in the next beta.

Thanks!
