### ISSUE TITLE
Flashable zip

### ISSUE THREAD

**Issue by Gaetanix** [corphish/NightLight#34]
Disclaimer: my knowledge on the subject is superficial and I may be about to say things that make no sense together, I say sorry in advance.

Is it possible to have a version that could be flashed on a custom recovery as a system app, so that it may work on non-rooted devices?

**Comment by corphish** [comment]
Since only way to talk to KCAL is by modifying its sysfs nodes, hence root is necessary to do this. I am not sure whether running it as a system app will let it modify without root.

However, I don't think it is completely impossible to have a non-root version of this. Maybe we can ship a system library (through a flashable zip) which will do the KCAL stuff and we can control the library via the app.

**Comment by Gaetanix** [comment]
Got it, thanks.
